import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { Button } from "../../components/Button";
import type { AiSubmissionDraft, ExtractionMode, SubmissionPreparation } from "./formSnapshotData";

type Stage = "document-select" | "document-info" | "required-upload" | "method" | "excel-upload" | "excel-summary" | "permits" | "invoice-info" | "additional" | "complete";
type ConversationEntry = { id: number; role: "assistant" | "user"; text: string };
type FileState = { name: string; size: number } | null;

const USER_SCOPE = { direction: "IMPORT", allowedDocuments: ["BC20", "BC16"], companyName: "PT Contoh Nusantara", npwp: "01.234.567.8-999.000", nib: "1234567890123" };
const DOCUMENTS = {
  BC20: { label: "BC 2.0", title: "PEMBERITAHUAN IMPOR BARANG UNTUK DIPAKAI (BC 2.0)", description: "Digunakan untuk pengeluaran barang impor dari Kawasan Pabean dengan tujuan diimpor untuk dipakai." },
  BC16: { label: "BC 1.6", title: "PEMBERITAHUAN IMPOR BARANG UNTUK DITIMBUN DI PUSAT LOGISTIK BERIKAT (BC 1.6)", description: "Digunakan untuk pemasukan barang impor untuk ditimbun di Pusat Logistik Berikat." },
} as const;
const REQUIRED_DOCUMENTS = [
  { id: "invoice", label: "Invoice", fullLabel: "Faktur Perdagangan (Invoice)" },
  { id: "packing_list", label: "Packing List", fullLabel: "Daftar Kemasan (Packing List)" },
  { id: "bill_of_lading", label: "B/L / AWB", fullLabel: "B/L (Bill of Lading) atau AWB" },
] as const;
const PERMIT_REQUIREMENTS: SubmissionPreparation["permitRequirements"] = [
  { hsCode: "8471.30.10", permitName: "Persetujuan Impor Produk Elektronik", customsCode: "PI-ELK", commodity: "Laptop Computer", regulation: "Permendag No. 21 Tahun 2025", description: "Komputer portabel dengan berat tidak lebih dari 10 kg.", note: "Wajib dipenuhi sebelum pengajuan diteruskan." },
  { hsCode: "8504.40.90", permitName: "Sertifikat Produk Penggunaan Tanda SNI", customsCode: "SPPT-SNI", commodity: "AC/DC Power Adapter", regulation: "Permenperin No. 18 Tahun 2024", description: "Static converter dan adaptor daya untuk perangkat elektronik.", note: "Dokumen akan diunggah pada Formulir Ekstraksi & Rincian." },
];
const INITIAL_CONVERSATION: ConversationEntry[] = [
  { id: 1, role: "assistant", text: "Selamat datang di Layanan Mandiri Pabean INSW." },
  { id: 2, role: "assistant", text: "Silakan pilih jenis dokumen pemasukan yang akan diajukan:" },
];
const STEPS = ["Dokumen", "Dokumen Wajib", "Data Barang", "Dokumen Tambahan", "Selesai"];

function BotIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-6 w-6 fill-current"><path d="M12 3.5A1.5 1.5 0 0 1 13.5 5v1H16a4 4 0 0 1 4 4v6a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4v-6a4 4 0 0 1 4-4h2.5V5A1.5 1.5 0 0 1 12 3.5Zm-1 3.5V6h2v1h-2Zm-2 3.5a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5Zm6 0a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5ZM9 15c0-1.1 1.34-2 3-2s3 .9 3 2H9Z" /></svg>; }
function AssistantBubble({ children }: { children: ReactNode }) { return <div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-brand-primary-50 text-brand-primary-600"><BotIcon /></div><div className="max-w-[780px] rounded-2xl rounded-tl-md border border-border-primary bg-white px-4 py-3 text-[12px] leading-6 text-neutral-800 shadow-sm">{children}</div></div>; }
function SectionCard({ eyebrow, title, description, children, tone = "default" }: { eyebrow: string; title: string; description?: ReactNode; children: ReactNode; tone?: "default" | "success" | "info" }) {
  const toneClass = tone === "success" ? "border-success-200 bg-success-50/40" : tone === "info" ? "border-brand-primary-200 bg-brand-primary-50/40" : "border-border-primary bg-white";
  return <section className={`rounded-[24px] border p-4 shadow-sm sm:p-6 ${toneClass}`}><div className="text-[10px] font-semibold uppercase tracking-[0.18em] text-brand-primary-600">{eyebrow}</div><h4 className="mt-2 text-[18px] font-semibold leading-7 text-neutral-800 sm:text-[20px]">{title}</h4>{description ? <div className="mt-2 max-w-3xl text-[12px] leading-6 text-neutral-600">{description}</div> : null}<div className="mt-5">{children}</div></section>;
}
function StatusBadge({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "success" | "warning" | "info" }) {
  const classes = { neutral: "bg-neutral-100 text-neutral-700", success: "bg-success-50 text-success-700", warning: "bg-amber-50 text-amber-800", info: "bg-brand-primary-50 text-brand-primary-700" };
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-semibold ${classes[tone]}`}>{children}</span>;
}
function FileRow({ label, value, accept, onChange }: { label: string; value: FileState; accept: string; onChange: (file: FileState) => void }) {
  return <div className="rounded-2xl border border-border-primary bg-background-primary/25 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2 text-[13px] font-semibold text-neutral-800">{label}<StatusBadge tone="warning">Wajib</StatusBadge></div><p className="mt-1 truncate text-[11px] text-neutral-500">{value ? `${value.name} · ${(value.size / 1024 / 1024).toFixed(2)} MB` : "Belum ada berkas dipilih"}</p></div><div className="flex shrink-0 items-center gap-2"><label className="cursor-pointer rounded-lg border border-brand-primary-300 bg-white px-3 py-2 text-[11px] font-semibold text-brand-primary-700 transition hover:bg-brand-primary-50">Pilih Berkas<input type="file" accept={accept} className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; onChange(file ? { name: file.name, size: file.size } : null); }} /></label>{value ? <StatusBadge tone="success">Berhasil diunggah</StatusBadge> : <StatusBadge>Menunggu</StatusBadge>}</div></div></div>;
}
function ConversationHistory({ entries }: { entries: ConversationEntry[] }) {
  const [expanded, setExpanded] = useState(true); const hiddenCount = Math.max(0, entries.length - 7); const visible = expanded || hiddenCount === 0 ? entries : entries.slice(-7);
  return <div className="space-y-3">{hiddenCount > 0 ? <button type="button" onClick={() => setExpanded((value) => !value)} className="mx-auto block rounded-full border border-brand-primary-200 bg-white px-4 py-2 text-[11px] font-semibold text-brand-primary-700 shadow-sm">{expanded ? "Ringkas percakapan" : `Lihat ${hiddenCount} jawaban sebelumnya`}</button> : null}{visible.map((entry) => entry.role === "assistant" ? <AssistantBubble key={entry.id}>{entry.text}</AssistantBubble> : <div key={entry.id} className="flex justify-end"><div className="max-w-[78%] rounded-2xl rounded-tr-md bg-brand-primary-600 px-4 py-3 text-[12px] leading-5 text-white shadow-sm">{entry.text}</div></div>)}</div>;
}

type Props = { open: boolean; onClose: () => void; onSubmit: (draft: AiSubmissionDraft, preparation: SubmissionPreparation) => void };

export function AiStepModal({ open, onClose, onSubmit }: Props) {
  const [stage, setStage] = useState<Stage>("document-select");
  const [selectedDocument, setSelectedDocument] = useState<keyof typeof DOCUMENTS | null>(null);
  const [requiredFiles, setRequiredFiles] = useState<Record<string, FileState>>({ invoice: null, packing_list: null, bill_of_lading: null });
  const [inputMethod, setInputMethod] = useState<ExtractionMode | null>(null);
  const [spreadsheet, setSpreadsheet] = useState<FileState>(null);
  const [hasAdditionalDocuments, setHasAdditionalDocuments] = useState<boolean | null>(null);
  const [conversation, setConversation] = useState<ConversationEntry[]>(INITIAL_CONVERSATION);
  const [openPermits, setOpenPermits] = useState<Record<string, boolean>>({ "8471.30.10": true });
  const scrollRef = useRef<HTMLDivElement>(null);
  const activeStep = useMemo(() => stage === "complete" ? 4 : stage === "additional" ? 3 : ["method", "excel-upload", "excel-summary", "permits", "invoice-info"].includes(stage) ? 2 : stage === "required-upload" ? 1 : 0, [stage]);
  const selectedInfo = selectedDocument ? DOCUMENTS[selectedDocument] : null;
  const requiredComplete = REQUIRED_DOCUMENTS.every((item) => requiredFiles[item.id]);
  const addConversation = (...entries: Array<Omit<ConversationEntry, "id">>) => setConversation((current) => [...current, ...entries.map((entry, index) => ({ ...entry, id: Date.now() + index }))]);

  useEffect(() => { if (!open) return; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = previous; }; }, [open]);
  useEffect(() => { if (!open) { setStage("document-select"); setSelectedDocument(null); setRequiredFiles({ invoice: null, packing_list: null, bill_of_lading: null }); setInputMethod(null); setSpreadsheet(null); setHasAdditionalDocuments(null); setConversation(INITIAL_CONVERSATION); } }, [open]);
  useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" }); }, [stage, conversation.length]);
  if (!open) return null;

  const chooseDocument = (code: keyof typeof DOCUMENTS) => { setSelectedDocument(code); addConversation({ role: "user", text: DOCUMENTS[code].label }, { role: "assistant", text: "Berikut informasi dokumen dan dokumen pelengkap pabean yang wajib disiapkan." }); setStage("document-info"); };
  const chooseMethod = (method: ExtractionMode) => { const label = method === "EXCEL" ? "Unggah Spreadsheet Excel" : "Ekstraksi Otomatis Invoice"; setInputMethod(method); addConversation({ role: "user", text: label }, { role: "assistant", text: method === "EXCEL" ? "Silakan unggah berkas rincian barang sesuai format template:" : "Ekstraksi otomatis akan dilanjutkan pada Formulir Ekstraksi." }); setStage(method === "EXCEL" ? "excel-upload" : "invoice-info"); };
  const continueToAdditional = () => { addConversation({ role: "assistant", text: "Apakah Anda memiliki Dokumen Fasilitas atau Dokumen Lainnya yang akan dilampirkan nanti?" }); setStage("additional"); };
  const chooseAdditional = (value: boolean) => { setHasAdditionalDocuments(value); addConversation({ role: "user", text: value ? "Ya" : "Tidak" }, { role: "assistant", text: "Persiapan pengajuan telah selesai. Silakan lanjut ke Formulir Ekstraksi & Rincian." }); setStage("complete"); };
  const handleHandoff = () => {
    if (!selectedDocument || !inputMethod || hasAdditionalDocuments === null) return;
    const uploadedDocuments = REQUIRED_DOCUMENTS.flatMap((item) => requiredFiles[item.id]?.name ?? []);
    const preparation: SubmissionPreparation = { documentType: selectedDocument, documentLabel: DOCUMENTS[selectedDocument].label, requiredDocuments: { invoice: requiredFiles.invoice ? { name: requiredFiles.invoice.name, size: requiredFiles.invoice.size } : undefined, packingList: requiredFiles.packing_list ? { name: requiredFiles.packing_list.name, size: requiredFiles.packing_list.size } : undefined, billOfLadingOrAwb: requiredFiles.bill_of_lading ? { name: requiredFiles.bill_of_lading.name, size: requiredFiles.bill_of_lading.size } : undefined }, inputMethod, spreadsheet: inputMethod === "EXCEL" && spreadsheet ? { fileName: spreadsheet.name, totalItems: 240, totalHsCodes: 4, totalCif: 42500, currency: "USD" } : null, permitRequirements: inputMethod === "EXCEL" ? PERMIT_REQUIREMENTS : [], hasAdditionalDocuments, extractionMode: inputMethod, initializationComplete: true };
    onSubmit({ jenisPengajuan: `${selectedInfo?.label} - ${selectedInfo?.title}`, namaPerusahaan: USER_SCOPE.companyName, npwp: USER_SCOPE.npwp, nib: USER_SCOPE.nib, keterangan: `Data disiapkan melalui Smart Submission Assistant. Metode: ${inputMethod}.`, dokumen: uploadedDocuments }, preparation); onClose();
  };

  return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/60 px-3 py-4 backdrop-blur-sm sm:px-4 sm:py-6"><div className="flex max-h-[calc(100vh-2rem)] w-full max-w-[1160px] flex-col overflow-hidden rounded-[28px] border border-white/70 bg-white shadow-[0_32px_90px_rgba(15,23,42,0.28)] sm:max-h-[calc(100vh-3rem)]">
    <header className="shrink-0 border-b border-border-primary bg-white px-5 py-4 sm:px-8 sm:py-5"><div className="flex items-start justify-between gap-4"><div><h3 className="text-[22px] font-semibold text-neutral-800 sm:text-[24px]">Smart Submission Assistant</h3><p className="mt-1 text-[12px] text-neutral-600">Asisten terpandu untuk menyiapkan data pengajuan berdasarkan akses dan dokumen Anda.</p></div><button type="button" aria-label="Tutup assistant" onClick={onClose} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-border-primary text-[20px] text-neutral-600 hover:bg-neutral-50">×</button></div><div className="mt-5 grid grid-cols-5 gap-1 sm:gap-3">{STEPS.map((label, index) => <div key={label} className="relative flex min-w-0 flex-col items-center">{index < STEPS.length - 1 ? <div className={`absolute left-1/2 top-4 h-px w-full ${index < activeStep ? "bg-brand-primary-500" : "bg-border-primary"}`} /> : null}<div className={`relative z-10 flex h-8 w-8 items-center justify-center rounded-full border text-[11px] font-semibold ${index <= activeStep ? "border-brand-primary-500 bg-brand-primary-500 text-white" : "border-border-primary bg-white text-neutral-500"}`}>{index < activeStep ? "✓" : index + 1}</div><div className={`mt-2 max-w-full truncate text-center text-[9px] font-medium sm:text-[11px] ${index <= activeStep ? "text-brand-primary-700" : "text-neutral-500"}`}>{label}</div></div>)}</div></header>
    <main ref={scrollRef} className="flex-1 overflow-y-auto bg-gradient-to-b from-brand-primary-50 to-brand-primary-100/50 px-4 py-5 sm:px-8"><div className="mx-auto max-w-[980px] space-y-4"><ConversationHistory entries={conversation} />

      {stage === "document-select" ? <SectionCard eyebrow="Langkah 1" title="Pemilihan Jenis Dokumen Pabean" description="Silakan pilih jenis dokumen pemasukan yang akan diajukan. Hanya dokumen sesuai scope akun SSO Anda yang ditampilkan."><div className="grid gap-3 sm:grid-cols-2">{USER_SCOPE.allowedDocuments.map((code) => { const option = DOCUMENTS[code as keyof typeof DOCUMENTS]; return option ? <button key={code} type="button" onClick={() => chooseDocument(code as keyof typeof DOCUMENTS)} className="rounded-2xl border border-border-primary bg-white p-4 text-left transition hover:-translate-y-0.5 hover:border-brand-primary-400 hover:shadow-md"><div className="text-[16px] font-semibold text-neutral-800">{option.label}</div><p className="mt-2 text-[11px] leading-5 text-neutral-600">{option.title}</p></button> : null; })}</div></SectionCard> : null}

      {stage === "document-info" && selectedInfo ? <SectionCard eyebrow="Informasi Dokumen" title={selectedInfo.title} description={selectedInfo.description}><div className="rounded-2xl border border-border-primary bg-background-primary/30 p-4"><h5 className="text-[13px] font-semibold text-neutral-800">Dokumen Pelengkap Pabean Wajib:</h5><ol className="mt-3 space-y-2 text-[12px] text-neutral-700">{REQUIRED_DOCUMENTS.map((item, index) => <li key={item.id} className="flex gap-3"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-brand-primary-100 text-[10px] font-semibold text-brand-primary-700">{index + 1}</span>{item.fullLabel}</li>)}</ol></div><div className="mt-5 flex flex-wrap justify-end gap-3"><Button variant="outline" size="sm" onClick={() => { addConversation({ role: "user", text: "Ubah Dokumen" }, { role: "assistant", text: "Silakan pilih kembali jenis dokumen pemasukan yang akan diajukan:" }); setStage("document-select"); }}>Ubah Dokumen</Button><Button variant="primary" size="sm" onClick={() => { addConversation({ role: "user", text: "Lanjutkan Unggah Berkas" }, { role: "assistant", text: "Silakan unggah seluruh dokumen pabean wajib." }); setStage("required-upload"); }}>Lanjutkan Unggah Berkas</Button></div></SectionCard> : null}

      {stage === "required-upload" ? <SectionCard eyebrow="Langkah 2" title="Unggah Dokumen Wajib" description={<>Silakan unggah seluruh dokumen pabean wajib<br /><span className="text-neutral-500">(Format: PDF, maks. 5MB per berkas):</span></>}><div className="space-y-3">{REQUIRED_DOCUMENTS.map((item) => <FileRow key={item.id} label={item.label} value={requiredFiles[item.id]} accept="application/pdf,.pdf" onChange={(file) => setRequiredFiles((current) => ({ ...current, [item.id]: file }))} />)}</div><div className="mt-5 flex justify-end"><Button variant="primary" size="sm" disabled={!requiredComplete} onClick={() => { addConversation({ role: "user", text: "3 dokumen wajib berhasil diunggah" }, { role: "assistant", text: "Dokumen wajib berhasil diunggah. Silakan tentukan metode pengisian elemen data rincian barang:" }); setStage("method"); }}>Simpan & Lanjutkan</Button></div></SectionCard> : null}

      {stage === "method" ? <SectionCard eyebrow="Langkah 3" title="Pemilihan Metode Input Data Barang" description="Dokumen wajib berhasil diunggah. Silakan tentukan metode pengisian elemen data rincian barang:"><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => chooseMethod("EXCEL")} className="rounded-2xl border border-border-primary bg-white p-5 text-left transition hover:border-brand-primary-400 hover:shadow-md"><div className="text-[14px] font-semibold text-neutral-800">Unggah Spreadsheet Excel</div><p className="mt-2 text-[11px] leading-5 text-neutral-600">Gunakan format standar untuk mengisi rincian barang secara terstruktur.</p></button><button type="button" onClick={() => chooseMethod("INVOICE_OCR")} className="rounded-2xl border border-border-primary bg-white p-5 text-left transition hover:border-brand-primary-400 hover:shadow-md"><div className="text-[14px] font-semibold text-neutral-800">Ekstraksi Otomatis Invoice</div><p className="mt-2 text-[11px] leading-5 text-neutral-600">Rincian barang akan dibaca dari Invoice pada formulir lanjutan.</p></button></div><button type="button" onClick={() => { const link = document.createElement("a"); link.href = `${import.meta.env.BASE_URL}template-upload-barang.xlsx`; link.download = "Template_Rincian_Barang_LNSW.xlsx"; link.click(); }} className="mt-4 text-[11px] font-semibold text-brand-primary-700 underline underline-offset-4">Unduh Format Standar: Template_Rincian_Barang_LNSW.xlsx</button></SectionCard> : null}

      {stage === "excel-upload" ? <SectionCard eyebrow="Data Barang · Jalur Excel" title="Unggah Spreadsheet Rincian Barang" description="Silakan unggah berkas rincian barang sesuai format template:"><label className="flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-brand-primary-300 bg-white px-5 py-8 text-center transition hover:bg-brand-primary-50"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-brand-primary-50 text-[24px] text-brand-primary-600">↑</span><span className="mt-3 text-[13px] font-semibold text-neutral-800">Klik atau seret berkas spreadsheet ke sini</span><span className="mt-1 text-[11px] text-neutral-500">Format didukung: .xlsx / .xls</span>{spreadsheet ? <span className="mt-3 rounded-full bg-success-50 px-3 py-1 text-[11px] font-semibold text-success-700">{spreadsheet.name}</span> : null}<input type="file" accept=".xlsx,.xls" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; setSpreadsheet(file ? { name: file.name, size: file.size } : null); }} /></label><div className="mt-5 flex justify-end"><Button variant="primary" size="sm" disabled={!spreadsheet} onClick={() => { addConversation({ role: "user", text: spreadsheet?.name ?? "Spreadsheet rincian barang" }, { role: "assistant", text: "Berkas berhasil dibaca. Berikut ringkasan validasi elemen barang." }); setStage("excel-summary"); }}>Lanjutkan</Button></div></SectionCard> : null}

      {stage === "excel-summary" ? <SectionCard eyebrow="Hasil Analisis" title="RINGKASAN VALIDASI ELEMEN BARANG"><div className="grid gap-3 sm:grid-cols-3">{[["Total Seri Barang", "12"], ["Total Pos Tarif (HS)", "3"], ["Total Nilai Barang (CIF)", "USD 42,500"]].map(([label, value]) => <div key={label} className="rounded-2xl border border-border-primary bg-white p-4"><div className="text-[10px] uppercase tracking-wide text-neutral-500">{label}</div><div className="mt-2 text-[20px] font-semibold text-neutral-800">{value}</div></div>)}</div><h5 className="mt-5 text-[13px] font-semibold text-neutral-800">Status Ketentuan & Regulasi:</h5><div className="mt-3 grid gap-3 sm:grid-cols-3">{[["Pos Tarif Wajib Lartas / Izin", "2", "warning"], ["Pos Tarif Bebas Lartas", "1", "success"], ["Pos Tarif Spesifikasi Khusus", "0", "info"]].map(([label, value, tone]) => <div key={label} className="rounded-xl border border-border-primary bg-white p-3"><StatusBadge tone={tone as "warning" | "success" | "info"}>{value} Pos Tarif</StatusBadge><p className="mt-2 text-[11px] text-neutral-700">{label}</p></div>)}</div><div className="mt-5 flex justify-end"><Button variant="primary" size="sm" onClick={() => { addConversation({ role: "user", text: "Lanjutkan" }, { role: "assistant", text: "Berdasarkan Pos Tarif yang diajukan, berikut daftar izin yang dipersyaratkan:" }); setStage("permits"); }}>Lanjutkan</Button></div></SectionCard> : null}

      {stage === "permits" ? <SectionCard eyebrow="Persyaratan Perizinan" title="Daftar Persyaratan Perizinan Pos Tarif" description="Berdasarkan Pos Tarif yang diajukan, berikut daftar izin yang dipersyaratkan:"><div className="space-y-3">{PERMIT_REQUIREMENTS.map((permit) => { const expanded = Boolean(openPermits[permit.hsCode]); return <div key={permit.hsCode} className="overflow-hidden rounded-2xl border border-border-primary bg-white"><button type="button" onClick={() => setOpenPermits((current) => ({ ...current, [permit.hsCode]: !expanded }))} className="flex w-full items-center justify-between gap-3 p-4 text-left"><div><div className="text-[10px] font-semibold uppercase tracking-wide text-brand-primary-600">Pos Tarif / HS Code</div><div className="mt-1 text-[14px] font-semibold text-neutral-800">{permit.hsCode} · {permit.commodity}</div></div><span className="text-[18px] text-neutral-500">{expanded ? "−" : "+"}</span></button>{expanded ? <div className="grid gap-3 border-t border-border-primary bg-background-primary/25 p-4 sm:grid-cols-2"><div><div className="text-[10px] text-neutral-500">Nama Izin</div><div className="mt-1 text-[12px] font-semibold text-neutral-800">{permit.permitName}</div></div><div><div className="text-[10px] text-neutral-500">Kode Izin Kepabeanan</div><div className="mt-1 text-[12px] text-neutral-800">{permit.customsCode}</div></div><div><div className="text-[10px] text-neutral-500">Regulasi</div><div className="mt-1 text-[12px] text-neutral-800">{permit.regulation}</div></div><div><div className="text-[10px] text-neutral-500">Keterangan</div><div className="mt-1 text-[12px] text-neutral-800">{permit.note}</div></div><div className="sm:col-span-2"><div className="text-[10px] text-neutral-500">Deskripsi</div><div className="mt-1 text-[12px] text-neutral-800">{permit.description}</div></div></div> : null}</div>; })}</div><div className="mt-5 flex justify-end"><Button variant="primary" size="sm" onClick={continueToAdditional}>Lanjutkan</Button></div></SectionCard> : null}

      {stage === "invoice-info" ? <SectionCard eyebrow="Data Barang · Jalur Ekstraksi Invoice" title="INFORMASI PEMROSESAN DATA BARANG" tone="info" description={<><p>Ekstraksi otomatis (OCR) rincian barang dari berkas Invoice akan dijalankan pada Formulir Ekstraksi.</p><p className="mt-2">Anda dapat memeriksa kesesuaian uraian barang serta penetapan Pos Tarif (HS Code) pada formulir tersebut.</p></>}><div className="grid grid-cols-4 items-center gap-2 rounded-2xl border border-brand-primary-100 bg-white p-4 text-center text-[10px] font-semibold text-brand-primary-700 sm:text-[12px]">{["Invoice", "OCR", "Rincian Barang", "HS Code"].map((label, index) => <div key={label} className="flex items-center gap-2"><span className="flex-1 rounded-lg bg-brand-primary-50 px-2 py-3">{label}</span>{index < 3 ? <span>→</span> : null}</div>)}</div><div className="mt-5 flex justify-end"><Button variant="primary" size="sm" onClick={continueToAdditional}>Lanjutkan</Button></div></SectionCard> : null}

      {stage === "additional" ? <SectionCard eyebrow="Langkah 4" title="Konfirmasi Dokumen Fasilitas / Tambahan" description={<><p>Apakah Anda memiliki Dokumen Fasilitas atau Dokumen Lainnya yang akan dilampirkan nanti?</p><p className="mt-1 text-neutral-500">(Contoh: Surat Keterangan Asal / COO, Laporan Surveyor, Polis)</p></>}><div className="rounded-xl border border-brand-primary-100 bg-brand-primary-50 p-3 text-[11px] leading-5 text-brand-primary-800">Catatan: Pengunggahan berkas dokumen tambahan akan dilakukan pada Formulir Lanjutan.</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => chooseAdditional(true)} className="rounded-2xl border border-border-primary bg-white p-4 text-left text-[14px] font-semibold text-neutral-800 hover:border-brand-primary-400">Ya</button><button type="button" onClick={() => chooseAdditional(false)} className="rounded-2xl border border-border-primary bg-white p-4 text-left text-[14px] font-semibold text-neutral-800 hover:border-brand-primary-400">Tidak</button></div></SectionCard> : null}

      {stage === "complete" && selectedInfo && inputMethod ? <SectionCard eyebrow="Langkah 5 · Selesai" title={`INISIALISASI PENGAJUAN ${selectedInfo.label} SELESAI`} tone="success" description={inputMethod === "EXCEL" ? <><p>Dokumen administrasi dan file Excel rincian barang telah berhasil dicatat ke dalam draf pengajuan.</p><p className="mt-2">Silakan menuju Formulir Lanjutan untuk meninjau rincian item barang, Pos Tarif, serta mengunggah berkas perizinan dan dokumen pendukung:</p></> : <><p>Seluruh dokumen administrasi awal telah tersimpan.</p><p className="mt-2">Silakan menuju Formulir Lanjutan untuk memulai proses OCR pembacaan barang, validasi Pos Tarif, serta unggah berkas dokumen perizinan / fasilitas:</p></>}><div className="grid gap-3 sm:grid-cols-4">{[["Dokumen", selectedInfo.label], ["Dokumen wajib", "3 file"], ["Metode barang", inputMethod === "EXCEL" ? "Spreadsheet Excel" : "Ekstraksi Invoice"], ["Dokumen fasilitas", hasAdditionalDocuments ? "Ada" : "Tidak Ada"]].map(([label, value]) => <div key={label} className="rounded-xl border border-success-200 bg-white p-3"><div className="text-[10px] text-neutral-500">{label}</div><div className="mt-1 text-[12px] font-semibold text-neutral-800">{value}</div></div>)}</div><div className="mt-5 flex justify-end"><Button variant="primary" size="md" onClick={handleHandoff}>{inputMethod === "EXCEL" ? "BUKA FORMULIR EKSTRAKSI & RINCIAN" : "BUKA FORMULIR EKSTRAKSI INVOICE"}</Button></div></SectionCard> : null}
    </div></main>
  </div></div>;
}
